// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var GamePage$ReactTemplate = require("./GamePage.bs.js");
var ListPage$ReactTemplate = require("./ListPage.bs.js");
var WordsPage$ReactTemplate = require("./WordsPage.bs.js");

var watcherID = ReasonReact.Router[/* watchUrl */1]((function (url) {
        var match = url[/* path */0];
        var exit = 0;
        if (match) {
          switch (match[0]) {
            case "game" : 
                if (match[1]) {
                  exit = 1;
                } else {
                  return ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, GamePage$ReactTemplate.make(/* array */[])), "index2");
                }
                break;
            case "lists" : 
                var match$1 = match[1];
                if (match$1) {
                  if (match$1[1]) {
                    exit = 1;
                  } else {
                    return ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, WordsPage$ReactTemplate.make(match$1[0], /* array */[])), "index2");
                  }
                } else {
                  return ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, ListPage$ReactTemplate.make(/* array */[])), "index2");
                }
                break;
            default:
              exit = 1;
          }
        } else {
          exit = 1;
        }
        if (exit === 1) {
          return ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, ListPage$ReactTemplate.make(/* array */[])), "index2");
        }
        
      }));

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, ListPage$ReactTemplate.make(/* array */[])), "index2");

exports.watcherID = watcherID;
/* watcherID Not a pure module */
