// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Header$ReactTemplate = require("./Header.bs.js");
var WordItem$ReactTemplate = require("./WordItem.bs.js");
var DataFetcher$ReactTemplate = require("./DataFetcher.bs.js");

var component = ReasonReact.statelessComponent("WordPage");

function make(id, _children) {
  var startGame = function ($$event, self) {
    DataFetcher$ReactTemplate.setListId(Caml_format.caml_int_of_string(id));
    return ReasonReact.Router[/* push */0]("/game");
  };
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var listId = Caml_format.caml_int_of_string(id);
              return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, Header$ReactTemplate.make("Words", /* array */[])), React.createElement("div", {
                              className: "listpage"
                            }, React.createElement("table", {
                                  className: "word_table"
                                }, React.createElement("tbody", undefined, Belt_Array.mapWithIndex(DataFetcher$ReactTemplate.getListWords(DataFetcher$ReactTemplate.getList(listId)), (function (index, word) {
                                            return ReasonReact.element(String(word[/* id */0]), undefined, WordItem$ReactTemplate.make(word[/* text */1], /* array */[]));
                                          }))))), React.createElement("div", {
                              className: "buttons"
                            }, React.createElement("button", {
                                  className: "button button-big button--primary",
                                  onClick: Curry._1(self[/* handle */0], startGame)
                                }, "Start")));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
